formation_exam:
    resource: "@FormationExamBundle/Resources/config/routing.yml"
    prefix:   /

formation_exam_admin:
    resource: "@FormationExamAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation

formation_sample_data_service:
    resource: "@FormationSampleDataServiceBundle/Resources/config/routing.yml"
    prefix:   /
