services:
#    formation_sample_data_service.example:
#        class: Formation\SampleDataServiceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    formation.sampledataservice:
        class: Formation\SampleDataServiceBundle\SampleDataService\SampleDataService
